### ISSUE TITLE
JSONObject["rightHand"] not a string.

### ISSUE THREAD

**Issue by apemanzilla** [Lemmmy/JRogue-issues#1]
I tried to eat a goblin corpse.

**Version:** alpha-0.3 (build Sat Feb 04 12:10:05 EST 2017)
**OS:** Linux (amd64)
**Java:** 1.8.0_121
**GL:** 3.0 Mesa 13.0.3 (X.Org)
**Trace:**
```
org.json.JSONException: JSONObject["rightHand"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:721)
	at jr.dungeon.entities.EntityLiving.unserialise(EntityLiving.java:212)
	at jr.dungeon.entities.monsters.Monster.unserialise(Monster.java:143)
	at jr.dungeon.items.comestibles.ItemCorpse.unserialise(ItemCorpse.java:211)
	at jr.dungeon.items.Item.createFromJSON(Item.java:132)
	at jr.dungeon.items.Item.copy(Item.java:213)
	at jr.dungeon.entities.player.visitors.PlayerEat.lambda$eatFromInventory$4(PlayerEat.java:94)
	at jr.dungeon.entities.player.visitors.PlayerItemVisitor$1.onResponse(PlayerItemVisitor.java:50)
	at jr.dungeon.Prompt.respond(Prompt.java:70)
	at jr.dungeon.Dungeon.promptRespond(Dungeon.java:385)
	at jr.rendering.gdx.GameInputProcessor.keyTyped(GameInputProcessor.java:199)
	at com.badlogic.gdx.InputMultiplexer.keyTyped(InputMultiplexer.java:84)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:75)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:190)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:380)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at jr.rendering.gdx.GDXRenderer.<init>(GDXRenderer.java:72)
	at jr.JRogue.start(JRogue.java:84)
	at jr.JRogue.<init>(JRogue.java:55)
	at jr.JRogue.main(JRogue.java:160)

```
**Whole Log:**
```
12:10:06 [main] INFO  - ---- Game started ----
12:10:06 [main] INFO  - JRogue version alpha-0.3, built Sat Feb 04 12:10:05 EST 2017

```

**Comment by Lemmmy** [comment]
fixed in b379987
